-- Hoppr seed places (mirror of src/core/places.ts). Idempotent.
insert into public.places (id, name, category, area, lat, lng, popularity, price, tags, blurb) values
  ('otterbein','Otterbein Coffee','cafe','Kerrytown',42.2864,-83.7434,0.86,2,
    '{coffee,quiet,bright,outlets,solo,lingering,study}','Quiet until noon, outlets everywhere, and nobody rushes you.'),
  ('marrow','Marrow & Ash','cafe','Old West Side',42.2789,-83.7561,0.72,2,
    '{coffee,quiet,bright,comfy,solo,lingering}','A hushed back room and a big communal table by the window.'),
  ('foldwell','Foldwell Books','study','Downtown',42.2801,-83.7488,0.64,1,
    '{study,quiet,moody,solo,lingering,comfy}','Reading nooks upstairs, warm lamps, and free tea refills.'),
  ('cadence','Cadence Tap','bar','Kerrytown',42.2871,-83.7419,0.79,2,
    '{drinks,lively,moody,group,hangout}','Low light, good vinyl, and it was half full an hour ago.'),
  ('halyard','Halyard House','restaurant','Main St',42.2802,-83.7476,0.83,3,
    '{food,lively,group,hangout,splurge}','Shared plates, buzzy, but you can still hear each other.'),
  ('juniper','Juniper Room','bar','Downtown',42.2795,-83.7452,0.70,3,
    '{drinks,moody,quiet,solo,splurge}','Small, warm, and a properly made negroni.'),
  ('westerly','Westerly Diner','restaurant','Westside',42.2758,-83.7689,0.68,1,
    '{food,cheap,lingering,bright,solo,group}','All-day breakfast, window booths, and nobody hurries you.'),
  ('lumen','Lumen Gallery Cafe','photo','Arts District',42.2833,-83.7401,0.66,2,
    '{coffee,photo,bright,quiet,hangout}','A skylight, plants, and quietly the most photogenic room in town.'),
  ('grainhaus','Grainhaus Bakery','bakery','Kerrytown',42.2869,-83.7447,0.81,1,
    '{coffee,cheap,quick,bright,solo}','Grab a laminated pastry and a filter coffee; in and out in ten.'),
  ('salt','Salt & Cedar','restaurant','Main St',42.2811,-83.7469,0.77,3,
    '{food,moody,group,splurge,hangout}','Candlelit, a little romantic, good for a slow group dinner.'),
  ('perch','The Perch','photo','Riverside',42.2914,-83.7327,0.60,2,
    '{photo,bright,hangout,group,lively}','Rooftop light at golden hour; bring a friend and a camera.'),
  ('stackhouse','Stackhouse Study Bar','study','Campus',42.2769,-83.7382,0.74,1,
    '{study,quiet,outlets,solo,lingering,cheap}','Silent floor with a plug at every seat and bottomless drip.'),
  ('moss','Moss & Maple','cafe','Burns Park',42.2681,-83.7351,0.69,2,
    '{coffee,bright,comfy,hangout,group,lingering}','Sunny corner spot, comfy couches, easy to lose an afternoon.'),
  ('emberline','Emberline','bar','Downtown',42.2807,-83.7441,0.82,2,
    '{drinks,lively,group,hangout,moody}','Gets loud after nine on a Friday — in the good way.')
on conflict (id) do nothing;
